"""Add category table and alter plant string

Revision ID: 00784fae9404
Revises: 9daae3dc8b96
Create Date: 2026-02-22 01:29:13.208557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '00784fae9404'
down_revision: Union[str, None] = '9daae3dc8b96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.alter_column('plants', 'category',
               existing_type=postgresql.ENUM('TREE', 'SHRUB', 'PALM', 'CREEPER', 'GROUNDCOVER', 'CLIMBER', 'FERN', 'GRASS', 'SUCCULENT', 'AQUATIC', 'OTHER', name='plantcategory'),
               type_=sa.String(),
               existing_nullable=False,
               postgresql_using="category::text")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plants', 'category',
               existing_type=sa.String(),
               type_=postgresql.ENUM('TREE', 'SHRUB', 'PALM', 'CREEPER', 'GROUNDCOVER', 'CLIMBER', 'FERN', 'GRASS', 'SUCCULENT', 'AQUATIC', 'OTHER', name='plantcategory'),
               existing_nullable=False,
               postgresql_using="category::plantcategory")
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
