"""remove_quantity_from_project_plants

Revision ID: 125e9ac25a44
Revises: a9e309cd3fb3
Create Date: 2026-02-21 15:32:41.314885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '125e9ac25a44'
down_revision: Union[str, None] = 'a9e309cd3fb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projectplants', 'quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projectplants', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
