"""add plant image urls

Revision ID: 2541828e4dd4
Revises: 125e9ac25a44
Create Date: 2026-02-21 22:00:48.981248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2541828e4dd4'
down_revision: Union[str, None] = '125e9ac25a44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plants', sa.Column('icon_url', sa.String(), nullable=True))
    op.add_column('plants', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plants', 'image_url')
    op.drop_column('plants', 'icon_url')
    # ### end Alembic commands ###
