"""add common_diseases to Plant model

Revision ID: 2feca7804718
Revises: 6decc685821f
Create Date: 2026-02-22 14:59:34.424219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2feca7804718'
down_revision: Union[str, None] = '6decc685821f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plants', sa.Column('common_diseases', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plants', 'common_diseases')
    # ### end Alembic commands ###
