"""add scientific_name to Plant model

Revision ID: 6decc685821f
Revises: 2d446705fee3
Create Date: 2026-02-22 12:35:00.272107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6decc685821f'
down_revision: Union[str, None] = '2d446705fee3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plants', sa.Column('scientific_name', sa.String(), nullable=True))
    op.alter_column('plants', 'taxon_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_plants_scientific_name'), 'plants', ['scientific_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plants_scientific_name'), table_name='plants')
    op.alter_column('plants', 'taxon_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('plants', 'scientific_name')
    # ### end Alembic commands ###
