"""Add created_at and updated_at to Taxon

Revision ID: 9daae3dc8b96
Revises: 2541828e4dd4
Create Date: 2026-02-22 00:59:13.438400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9daae3dc8b96'
down_revision: Union[str, None] = '2541828e4dd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taxons', sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('taxons', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('taxons', 'updated_at')
    op.drop_column('taxons', 'created_at')
    # ### end Alembic commands ###
