"""Initial migration

Revision ID: e8ff6e633003
Revises: 
Create Date: 2026-02-19 02:17:47.062963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8ff6e633003'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taxons',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('rank', sa.Enum('KINGDOM', 'DIVISION', 'CLASS', 'ORDER', 'FAMILY', 'GENUS', 'SPECIES', name='rank'), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['taxons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_taxons_name'), 'taxons', ['name'], unique=False)
    op.create_index(op.f('ix_taxons_parent_id'), 'taxons', ['parent_id'], unique=False)
    op.create_index(op.f('ix_taxons_rank'), 'taxons', ['rank'], unique=False)
    op.create_table('plants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('taxon_id', sa.Uuid(), nullable=False),
    sa.Column('common_name', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('TREE', 'SHRUB', 'PALM', 'CREEPER', 'GROUNDCOVER', 'CLIMBER', 'FERN', 'GRASS', 'SUCCULENT', 'AQUATIC', 'OTHER', name='plantcategory'), nullable=False),
    sa.Column('planting_place', sa.Enum('INDOOR', 'OUTDOOR', 'BOTH', name='plantingplace'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('care_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['taxon_id'], ['taxons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plants_category'), 'plants', ['category'], unique=False)
    op.create_index(op.f('ix_plants_common_name'), 'plants', ['common_name'], unique=False)
    op.create_index(op.f('ix_plants_planting_place'), 'plants', ['planting_place'], unique=False)
    op.create_index(op.f('ix_plants_taxon_id'), 'plants', ['taxon_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plants_taxon_id'), table_name='plants')
    op.drop_index(op.f('ix_plants_planting_place'), table_name='plants')
    op.drop_index(op.f('ix_plants_common_name'), table_name='plants')
    op.drop_index(op.f('ix_plants_category'), table_name='plants')
    op.drop_table('plants')
    op.drop_index(op.f('ix_taxons_rank'), table_name='taxons')
    op.drop_index(op.f('ix_taxons_parent_id'), table_name='taxons')
    op.drop_index(op.f('ix_taxons_name'), table_name='taxons')
    op.drop_table('taxons')
    # ### end Alembic commands ###
